#include "Player.h"

//Player constructor. It takes the inputed name, the pair containing their starting position and the cardinal position
Player::Player(string name, pair<int, int> startingPosition, int cardinalPosition) {
	this->name = name;
	this->score = 0;
	this->numberOfCollectedTreasures = 0;
	this->isKeyObtained = false;
	this->isCollided = false;
	this->motion = { false,false,false,false };
	this->boundingSphereRadius = 1.5;
	this->hasWon = false;
	findStartingPosition(startingPosition, cardinalPosition);
}

//This function lets us find the starting position of the player.
//Player's Yaw value is set to a specific value depending on the cardinal position of the startin position
//generated by the Maze class.
void Player::findStartingPosition(pair<int, int> beginningTileCoords, int cardinalPosition) {
	GLfloat x_coordinate = 0.0, z_coordinate = 0.0;
	x_coordinate = (get<0>(beginningTileCoords));
	z_coordinate = -(get<1>(beginningTileCoords));
	switch (cardinalPosition) {
		case 0: //NORTH
			this->yaw = 90.0;
			break;
		case 1: //EAST
			this->yaw = 0.0;
			break;
		case 2: //SOUTH
			this->yaw = -90.0;
			break;
		case 3: //WEST
			this->yaw = 180.0;
			break;
	}
	this->coordinates = make_pair(x_coordinate, z_coordinate);
	this->pitch = 0.0;
}